### PR TITLE
Use globalThis code in place of global

### PR DESCRIPTION
**Pull request by RMacfarlane**
Fixes https://github.com/crypto-browserify/randombytes/issues/22

### CODE REVIEW

**Comment by jimmywarting** [comment]
should just use `globalThis` and if it isn't supported one should just do

`self.globalThis = self`
`window.globalThis = window`
`global.globalThis = global`

in top of their script runtime

**Comment by calvinmetcalf** [comment]
this is intended for use with a bundler which should handle this sort of thing, are you having problems somewhere

**Comment by RMacfarlane** [comment]
I'm using webpack and targeting `webworker`. The bundler does not do any sort of shim for global, in a webworker the only way to access the global object is `self`.

**Comment by calvinmetcalf** [comment]
Webpack 100% provides a global shim, and will provide it once to be shared
by all your code, have you either turned this off? Or has web pack maybe
decided to break stuff by turning it off by default?

**Comment by RMacfarlane** [comment]
Perhaps unintentionally.

IMO, I shouldn't have to fiddle with my bundler to get this code to run in a browser context, it should be able to do so without outside intervention.

**Comment by calvinmetcalf** [comment]
I know for a fact that this has worked with webpack in the past. So if it's
not working out of the box anymore that could be a webpack change that will
effect a lot of other libraries. I can look into it more but not until
after labor day.

**Comment by RMacfarlane** [comment]
Thanks!

Here's the webpack config I'm using, I may just be doing something stupid: https://github.com/microsoft/vscode/blob/616afa93e2da5a5a92b14863bab8b339b977edc4/extensions/microsoft-authentication/extension-browser.webpack.config.js

That being said, I think it's pretty easy to misconfigure webpack, and it would be helpful to others if there wasn't direct `global` usage that needs to be shimmed

**Comment by calvinmetcalf** [comment]
what version of webpack is this ?

**Comment by RMacfarlane** [comment]
4.43.0

**Comment by calvinmetcalf** [comment]
I think you turned it off [here](https://github.com/microsoft/vscode/blob/616afa93e2da5a5a92b14863bab8b339b977edc4/extensions/microsoft-authentication/extension-browser.webpack.config.js#L15)

**Comment by RMacfarlane** [comment]
If you don't intend to accept fixes for https://github.com/crypto-browserify/randombytes/issues/22, please close it, then.

**Pull request closed without merging**
