### PR TITLE
Fix crypto global detection

### PR DESCRIPTION
**Pull request by feross**
Recent changes to crypto-browserify make browserify tests fail. This
fixes them.

### CODE REVIEW

**Comment by jprichardson** [comment]
ACK

**Comment by calvinmetcalf** [comment]
Yeah looks good, can merge and publish later tonight or first thing tommorow unless somebody beats me to it. 

Curious how this gets triggered as this file shouldn't actually be run in a non browser context

**Comment by dcousens** [comment]
ACK.

This would fail in a browser that doesn't have `window.crypto` because `crypto` is undefined and therefore `.getRandomValues` is also undefined, leading to the `undefined` error.

**Comment by calvinmetcalf** [comment]
@dcousens are you able to publish?

**Comment by feross** [comment]
Right. It fails the browserify tests too because they run the browserified
code in node with vm.runInContext where a crypto global is also lacking.

**Comment by dcousens** [comment]
Published as [2.0.1](https://github.com/crypto-browserify/randombytes/commit/849c4a44af3275dd1fa5ae221e5e87304b43e165)

**Comment by dcousens** [comment]
@calvinmetcalf we should probably find a way to test in the same way, to avoid our dependents finding this out for us.

**Comment by feross** [comment]
Thanks for the quick fix and merge.

**Pull request merged**
